name: First CI pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Run hello script
        run: echo "CI Pipeline executed successfully!"

      #   - name: Run shell script
      #     run: bash module-2-linux/system_summary.sh

      - name: Install tree
        run: sudo apt update & sudo apt install tree -y

      - name: List folder structure
        run: tree .
